### PR TITLE
Assignment-1 added

### PR DESCRIPTION
**Pull request by shruthanr**
Added assignment-1 notebook

### CODE REVIEW

**Comment by YashasG98** [comment]
- You do not need prerequisite football knowledge to work with the data. Most of the times you will come across data which you don't have a single clue about, what and how well you make of it is what defines your skill, and you did a pretty good job.
- Not done question 4 and 8 (if it was a problem, contact me)
- Try the open question if you want to explore more
Other than that, brilliant work!

**Comment by YashasG98** [comment]
If you know how to do 4 and 8, which you most probably do, just comment here, and I'll merge, OR I'll wait for another PR.

**Review by YashasG98 — APPROVED** [review]

**Comment by YashasG98** [comment]
4 and 8 are fine, but 5 seems to be wrong, check it out.

**Comment by shruthanr** [comment]
Should have used .sum() instead of .count()

**Pull request merged**
